### ISSUE TITLE
Replace .bind() with arrow function to return correct type

### ISSUE THREAD

**Issue by ryanwoodcox** [bonjurmrfirst/angular4-carousel#13]
In the window-width.service.ts file, replace line 19:
.map(this.assertSize.bind(this, scrollBar))
with:
.map(() => this.assertSize(scrollBar))

After upgrading angular packages and peer dependencies, the build is more strict and does not like returning an Observable<{}> in a function that returns Observable<boolean>.

**Comment by bonjurmrfirst** [comment]
resloved
