### ISSUE TITLE
Add support for dynamic input data

### ISSUE THREAD

**Issue by ryanwoodcox** [bonjurmrfirst/angular4-carousel#14]
Consider implementing OnChanges in order to reinitialize the input data when an @Input() property such as sources (the array of images), or the configuration.

I've accomplished this by simply calling this.initData() when any @Input() changes:
  ngOnChanges() {
    this.initData();
  }

**Comment by dockleryxk** [comment]
@ryanwoodcox would you submit a PR for this?

**Comment by ryanwoodcox** [comment]
@dockleryxk Sure, PR is in.
