### ISSUE TITLE
How to start autoplay dynamically?

### ISSUE THREAD

**Issue by tasoskakour** [bonjurmrfirst/angular4-carousel#15]
Hey!

My initial config is this: 

`public config: ICarouselConfig = {
    verifyBeforeLoad: true,
    log: false,
    animation: true,
    animationType: AnimationConfig.SLIDE,
    autoplay: false,
    autoplayDelay: 4000,
    stopAutoplayMinWidth: 768
  };`

I want to enable autoplay when a user clicks a button. 
I tried setting **this.config.autoplay = true**, when user clicks the button, but it doesn't seem to work.

**Comment by dockleryxk** [comment]
Duplicate of #14
