### ISSUE TITLE
browser issues

### ISSUE THREAD

**Issue by carlosdv4** [bonjurmrfirst/angular4-carousel#19]
Some issues with the next and prev on chrome, samsung tab, some safari mac versions

on ipads after you click the next or previous image the image carousel stops looping.

Also seems not natural the scrolling of images, seem's like if there is a friction, is not smooth.

The carousel crash the app or browsers in all mobiles and tablets. Maybe there is a memory leak somewhere.

**Comment by dockleryxk** [comment]
Could you supply some sample code to reproduce these issues? I'm not able to recreate this.

**Comment by carlosdv4** [comment]
I load your demo page on each device and test each one in different browsers. Don't use the responsive views from the browser, I test on the device itself.

**Comment by dockleryxk** [comment]
I understand. I have looked with multiple devices and don't have an issue.

**Comment by dockleryxk** [comment]
I am no longer supporting this package, perhaps @bonjurmrfirst will. If not you can check out [this slideshow](https://github.com/dockleryxk/ng-simple-slideshow) I will be supporting. At any rate, I will close this now.
