### ISSUE TITLE
Error : Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by skyjich** [bonjurmrfirst/angular4-carousel#2]
Hi.. I followed your install and setting guid.. but not view the image.. 
and there were error message on the console.. Check the error and let me know how to fix it..

core.es5.js:1084 ERROR TypeError: Cannot read property 'concat' of undefined
    at SafeSubscriber._next (carousel.component.ts:25)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:236)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at Subject.next (Subject.js:55)
    at CarouselService.init (carousel.service.ts:26)
    at CarouselComponent.ngOnInit (carousel.component.ts:33)
    at checkAndUpdateDirectiveInline (core.es5.js:10727)
    at checkAndUpdateNodeInline (core.es5.js:12117)

* on this package.json 

{
  "name": "autocodi.com",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 8080",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@covalent/core": "^1.0.0-beta.3-2",
    "angular4-carousel": "^2.2.5",
    "angularfire2": "^4.0.0-rc.0",
    "core-js": "^2.4.1",
    "firebase": "^3.9.0",
    "firebaseui": "^1.0.1",
    "firebaseui-angular": "^0.2.0",
    "hammerjs": "^2.0.8",
    "history": "^4.6.1",
    "md2": "0.0.19",
    "primeng": "^4.0.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

**Comment by bonjurmrfirst** [comment]
@skyjich 
Hi,
I tested 2.2.5 in all common browsers and found no error.

Please update carousel to latest version ( v3.0.0 ), there is some changes related to concat.
I hope updating solve this. If not - please upload your carousel config.

In 3.0.0 added prop 'stopAutoplayMinWidth' to config interface, so you need to add this prop to your config (see details in readme.md).
