### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jbojcic1** [bonjurmrfirst/angular4-carousel#20]
I followed installation steps and I am getting the following error:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /.../node_modules/angular4-carousel/node_modules/@angular/core/core.d.ts, resolving symbol CarouselModule in /.../node_modules/angular4-carousel/src/app/index.ts, resolving symbol CarouselModule in /.../node_modules/angular4-carousel/src/app/index.ts

Am I doing something wrong or there is a bug?

**Comment by dockleryxk** [comment]
I am no longer supporting this package, perhaps @bonjurmrfirst will. If not you can check out [this slideshow](https://github.com/dockleryxk/ng-simple-slideshow) I will be supporting

**Comment by jbojcic1** [comment]
Ok. Will check it out. Thx

**Comment by bonjurmrfirst** [comment]
Hi,
can't reproduce an error

**Comment by bonjurmrfirst** [comment]
@dockleryxk, thx for supporting, I appreciate

**Comment by kapr1k0rn** [comment]
@bonjurmrfirst Hi,
I am getting the same error. To reproduce the error,
1.ng new carousel
2.npm install angular4-carousel --save
3.import module and write some code to use carousel in app.component.

**Comment by bonjurmrfirst** [comment]
Hi, @kapr1k0rn 
Looks like issue resolved by updating cli.

Closed.

**Comment by MohitKS5** [comment]
same error in angular 1.6.0

**Comment by HKSultan** [comment]
same error in angular cli 1.7.3
