### ISSUE TITLE
Multiple carousels at one page

### ISSUE THREAD

**Issue by gasperthegracner** [bonjurmrfirst/angular4-carousel#22]
Maybe you noticed a problem with adding multiple components into a single page? In my case all images are loaded in one carousel, other two are empty.

**Comment by bonjurmrfirst** [comment]
Hi, I don't think its possible. Services are singletons, when you pass carousel config to service, you overwrite previous config.

**Comment by dockleryxk** [comment]
That sucks because this is truly a great carousel. [Here](https://www.npmjs.com/package/ng-simple-slideshow) is an alternative though
