### ISSUE TITLE
Javascript file in the package.

### ISSUE THREAD

**Issue by JudeAlquiza** [bonjurmrfirst/angular4-carousel#3]
Hi,

     Just want to ask if there is an included javascript file in the package?

Thanks!
Jude Alquiza.

**Comment by bonjurmrfirst** [comment]
@JudeAlquiza Hi,
Only typescript files included.

**Comment by JudeAlquiza** [comment]
Thanks 

just want to confirm how to make this work in prod if there are no javascript files to reference when loading with systemJS?
