### ISSUE TITLE
Angular 4.3.3 Update

### ISSUE THREAD

**Issue by sahinyanlik** [bonjurmrfirst/angular4-carousel#7]
When I use with angular 4.3.3 with typscript 2.4.2 
I get 
Type 'Observable<{}>' is not assignable to type 'Observable<boolean>'.
  Type '{}' is not assignable to type 'boolean'.

In window-width.service.ts file.

**Comment by ferdibejtullahu** [comment]
Go to node_modules/angular4-carousel,
open file window-width.service.ts on line 14 change  from
public onResize(minWidthBreakpoint: number, scrollBar?: boolean): Observable {
to
public onResize(minWidthBreakpoint: number, scrollBar?: boolean): Observable<boolean | {}> {

**Comment by dockleryxk** [comment]
@ferdibejtullahu or @sahinyanlik could one of you submit a pull request? I can check then

**Comment by dockleryxk** [comment]
Nevermind, I got it
