### ISSUE TITLE
enableProdMode() called from app/index.ts no matter what

### ISSUE THREAD

**Issue by dockleryxk** [bonjurmrfirst/angular4-carousel#9]
Why is this call here? It does not make sense to me. PR submitted: #8

**Comment by dockleryxk** [comment]
@bonjurmrfirst you can close this, apologies for the bad formatting on the commit. 

Also, if you want help managing this repo/npm page let me know. I have a direct interesting in keeping it going! If not, no worries. I will keep contributing either way 🙃

**Comment by bonjurmrfirst** [comment]
@dockleryxk I don't have enough time to support carousel, so I'd appreciate it if you join :).

**Comment by dockleryxk** [comment]
Sounds good, my username on npm is bichard and my email is rajeffords@gmail.com if you need to contact me
